version: 1
disable_existing_loggers: true



formatters:
    standard:
        format: "%(asctime)s - %(levelname)s <PID %(process)d:%(processName)s> - %(threadName)s - %(name)s - %(levelname)s - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    ##info_file_handler:
        #class: logging.handlers.TimedRotatingFileHandler
        #level: INFO
        #filename: info.log
        #when: 'midnight'
        #backupCount: 4
        #utc: True
        #filters: [infoFilter]
        #encoding: utf8

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: /var/log/log.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8


root:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: yes

#loggers:
    #<module>:
       # level: INFO
        #handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        #propagate: no
