##############
#   Images   #
##############
# number of images per .h5 file
images_per_storage =  100000
# image shape for model input
image_shape = [224,224,3]

###############
#  Captions   #
###############
start_seq = "startseq"
end_seq = "endseq"

##############
# ../config  #
##############
# path to the logging config file
log_config = "../config/logConfig.yml"

##############
# ../data    #
##############
# path to the repertory containing the .h5 data (image/caption)
data_path = "../data/"

# full path to the tsv (raw data files)
train_raw_data = "../data/rawdata/GCC-training.tsv"
validation_raw_data = "../data/rawdata/GCC-validation.tsv"

##########################
#  Embedding parameters  #
##########################
glove_embed_data = "./preprocessor.pickle"
glove_dir = "../data/glove"
glove_url = 'http://nlp.stanford.edu/data/glove.6B.zip'

MAX_SEQUENCE_LENGTH = 34
EMBEDDING_SIZE = 50
MAX_VOCAB_SIZE= 10000

######################
#  Model parameters  #
######################
model_path = "../models/"
refit_path = "../data/checkpoints/"

LOSS = "categorical_crossentropy"
LEARNING_RATE = 0.001

#################
#  TensorBoard  #
#################
#tensorboard_log_dir='/var/log/TensorBoard'
tensorboard_log_dir='s3://sagemaker-studio-3fqzdvw0h4y/capstone-prototype/data/tensorboard'